# Generated by Django 3.2.5 on 2022-09-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_sum',
            field=models.IntegerField(db_column='menu_sum', default=0),
        ),
    ]
