# Generated by Django 3.2.5 on 2022-09-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_cusord_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instock',
            name='in_time',
            field=models.DateField(auto_now_add=True, db_column='inTime'),
        ),
        migrations.AlterField(
            model_name='ord',
            name='in_time',
            field=models.DateField(auto_now_add=True, db_column='inTime'),
        ),
        migrations.AlterField(
            model_name='outstock',
            name='out_time',
            field=models.DateField(auto_now_add=True, db_column='outTime'),
        ),
    ]
