# Generated by Django 3.2.5 on 2022-09-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_material_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instock',
            name='in_quan',
            field=models.IntegerField(db_column='inQuan', default=0),
        ),
        migrations.AlterField(
            model_name='outstock',
            name='out_quan',
            field=models.IntegerField(db_column='outQuan', default=0),
        ),
    ]
